### ISSUE TITLE
Cannot Parse log_analytics_workspace_id as resource id

### ISSUE THREAD

**Issue by paddyhitch** [avinor/terraform-azurerm-virtual-network-hub#1]
Getting the following error:

Error: Can not parse "log_analytics_workspace_id" as a resource id: Cannot parse Azure ID: parse log_id: invalid URI for request

  on ..\Modules\vnet_hub\main.tf line 324, in resource "azurerm_monitor_diagnostic_setting" "mgmt":
 324: resource "azurerm_monitor_diagnostic_setting" "mgmt" {

For the advanced-use example, do I need to have a log analytics workspace already created?

**Comment by tesharp** [comment]
Do you get this error when not setting log_analytics_workspace_id variable at all? Also which version of this template are you using.. In updated template that resource is not on line 324

It is required that log analytics workspace already exists yes. That can be created with https://github.com/avinor/terraform-azurerm-log-analytics template

**Comment by paddyhitch** [comment]
Figured out the issue. For me, it was switching data.azurerm_log_analytics_workspace.log_aw.workspace_id to data.azurerm_log_analytics_workspace.log_aw.id
